import {useEffect, useState} from 'react'
import {Icon, list, obj, number} from '../ui'
import type {JsonRecord} from '../api'
import './north-story.css'

const value=(x:unknown)=>typeof x==='number'?x:0
const text=(x:unknown)=>typeof x==='string'?x:''
const methodNames:Record<string,string>={hydroponics:'Topraksız',greenhouse:'Sera',open_field:'Açık tarla'}
export const waterLabel=(x:unknown)=>value(x)>0&&value(x)<.05?'<0,1 m³':`${number(x)} m³`
const signed=(x:number,d=1)=>Math.abs(x)<.5*10**(-d)?'0':`${x>0?'+':''}${number(x,d)}`

export function FutureTimeline({request}:{request:JsonRecord}){
  const [data,setData]=useState<JsonRecord|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[baseline,setBaseline]=useState('recent')
  const key=JSON.stringify({...request,horizon_id:'mid'})
  useEffect(()=>{const abort=new AbortController();setData(null);setError('');fetch('/api/north/timeline',{method:'POST',headers:{'Content-Type':'application/json'},body:key,signal:abort.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:'Dönemler karşılaştırılamadı.');return body}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>abort.abort()},[key,retry])
  const points=list(data?.points),selected=points.find(p=>p.horizon_id===(request.target_year?'year':request.horizon_id)),baseId=baseline===(request.target_year?'year':request.horizon_id)?(request.horizon_id==='historical'?'near':'historical'):baseline,base=points.find(p=>p.horizon_id===baseId)
  const a=obj(base?.totals),b=obj(selected?.totals),hasPlans=base?.status!=='infeasible'&&selected?.status!=='infeasible'&&Boolean(base&&selected)
  const deltaCrops=hasPlans?[...new Set([...list(base?.crops),...list(selected?.crops)].map(c=>text(c.id)))].map(id=>{const before=list(base?.crops).find(c=>c.id===id),after=list(selected?.crops).find(c=>c.id===id);return {name:text(after?.name)||text(before?.name),delta:value(after?.share_pct)-value(before?.share_pct)}}).filter(c=>Math.abs(c.delta)>=.1).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)):[]
  return <section className="north-future-story" aria-label="Dönemler arasında gerçek üretim değişimi"><header><b><Icon name="north" size={15}/>Üretim gelecekte nasıl değişiyor?</b><small>Aynı alan · aynı amaç · {request.scenario_id==='ssp585'?'SSP5-8.5':'SSP2-4.5'}</small></header>
    {!data?<div className="north-timeline-wait" role="status">{error?<>{error} <button onClick={()=>setRetry(n=>n+1)}>Yeniden dene</button></>:'Seçilen yıl ve iklim dönemleri aynı motorla karşılaştırılıyor…'}</div>:<><div className="north-periods">{points.map(p=><div key={text(p.horizon_id)} className={p.horizon_id===(request.target_year?'year':request.horizon_id)?"selected":""}><span><b>{text(p.label)}{['near','mid','late'].includes(text(p.horizon_id))?' dönemi':''}</b><small>{text(p.period)}</small></span><div className="north-method-track" aria-label={Object.entries(obj(p.method_shares_pct)).map(([m,s])=>`${methodNames[m]} %${number(s)}`).join(', ')}>{Object.entries(obj(p.method_shares_pct)).map(([m,s])=><i key={m} className={m} style={{width:`${value(s)}%`}}/>)}</div><small className="north-period-dominant">{p.status==='infeasible'?'Kaynakları gözden geçir':Object.entries(obj(p.method_shares_pct)).filter(([,s])=>value(s)>=.1).map(([m,s])=>`${methodNames[m]} %${number(s,0)}`).join(' · ')}</small><small className="north-period-frontier">{list(obj(p.frontier).crops).filter(c=>c.crop_id==="potato"&&typeof c.model_years_evaluated==="number").map(c=><span key="potato">Patates iklim ön elemesi {number(c.model_years_passing,0)}/{number(c.model_years_evaluated,0)}</span>)}</small></div>)}</div>
      <div className="north-timeline-compare"><label>Karşılaştır <select aria-label="Karşılaştırma başlangıç dönemi" value={baseId} onChange={e=>setBaseline(e.target.value)}>{points.filter(p=>p.horizon_id!==(request.target_year?'year':request.horizon_id)).map(p=><option key={text(p.horizon_id)} value={text(p.horizon_id)}>{text(p.label)}</option>)}</select><Icon name="arrow" size={12}/><b>{text(selected?.label)}</b></label>{hasPlans?<div className="north-delta-chips"><span>Sera <b>{signed(value(obj(selected?.method_shares_pct).greenhouse)-value(obj(base?.method_shares_pct).greenhouse))} puan</b></span><span>Yeni su <b>{signed(value(b.water_m3)-value(a.water_m3))} m³/yıl</b></span><span>Isı <b>{value(a.heat_kwh_th)>0?`${signed((value(b.heat_kwh_th)/value(a.heat_kwh_th)-1)*100)}%`:'başlangıç sıfır'}</b></span><span title="Elektrik + ısı / seçilen COP. Birincil enerji değildir.">Elektrik eşd. <b>{value(a.equivalent_electricity_kwh)>0?`${signed((value(b.equivalent_electricity_kwh)/value(a.equivalent_electricity_kwh)-1)*100)}%`:"—"}</b></span><span>Depodan pay <b>{signed(value(selected?.stored_share_pct)-value(base?.stored_share_pct))} puan</b></span></div>:<small>Uygulanabilirlik değişti; yetersiz plan sayısal sıfır kabul edilmez.</small>}</div>
      <div className="north-crop-shift">{hasPlans?(deltaCrops.length?deltaCrops.slice(0,3).map(c=><span key={c.name}>{c.delta>0?'↑':'↓'} {c.name} {signed(c.delta)} puan</span>):<span>Ürün payları korunuyor.{Math.abs(value(obj(selected?.method_shares_pct).greenhouse)-value(obj(base?.method_shares_pct).greenhouse))>=.1?` Yöntem önerisi: sera payını %${number(obj(base?.method_shares_pct).greenhouse)} → %${number(obj(selected?.method_shares_pct).greenhouse)} ${value(obj(selected?.method_shares_pct).greenhouse)>value(obj(base?.method_shares_pct).greenhouse)?"artır":"azalt"}.`:" Yöntem payları da korunuyor."}</span>):null}<small>Yakın dönem: ERA5 2015–2025. NASA geleceğiyle fark veri seti/hücre etkisini de içerir. Tarihsel NASA: 1995–2014. Isı farkı seçilen yöntemden de etkilenir.</small></div></>}
  </section>
}

export function ClimateFrontier({candidates}:{candidates:JsonRecord}){
  const rows=list(obj(candidates.climate_frontier).crops).filter(c=>['barley','potato','wheat'].includes(text(c.crop_id)))
  return <section className="north-frontier" aria-label="İklim adayı ve kaynak filtresi"><div className="north-frontier-label"><Icon name="sun" size={16}/><b>İklim sınırı</b><small>Açık tarla araştırması</small></div><div className="north-frontier-crops">{rows.map(c=><details key={text(c.crop_id)}><summary><b>{text(c.name_tr)}</b><span>{c.status==='screened_out'?'Ön elemede eşik altında':c.status==='potential'?'İklim potansiyeli açılıyor':c.status==='candidate'?'İklim adayı':'İklim eşiği doğrulanmalı'}</span>{typeof c.model_years_evaluated==='number'&&<small>{number(c.model_years_passing,0)}/{number(c.model_years_evaluated,0)} model-yıl ön elemeyi geçti</small>}</summary><p>{text(c.reason)}</p><p>{list(c.tests).map(t=>text(t.label)||text(t.id)).join(' · ')}</p><p>Zemin, su ve yerel verim doğrulanmadan açık tarla alanı önerilmez. Model-yıl sayısı başarı olasılığı değildir.</p></details>)}</div><div className="north-frontier-filter"><Icon name="arrow" size={15}/><span>Su · zemin · enerji filtresi</span><Icon name="arrow" size={15}/><b>Koşullu üretim planı ↓</b></div></section>
}

export function DecisionActions({story}:{story:JsonRecord}){
  const security=obj(story.water_security),stored=list(security.sources).find(s=>s.id==="stored_precipitation"),sea=list(security.sources).find(s=>s.id==="desalinated_seawater"); const actions=list(story.actions),selected=['production','water','infrastructure','risk'].map(kind=>actions.find(a=>kind==='risk'?a.id==='sensitivity':a.kind===kind)||actions.find(a=>a.kind===kind)).filter((a):a is JsonRecord=>Boolean(a)),dominant=list(obj(story.production).crops)[0]
  return <div className="north-action-list">{selected.map(a=><details key={text(a.id)} className={text(a.tone)}><summary><span>{({production:'ÜRETİM',water:'SU',infrastructure:'ALTYAPI',risk:'RİSK'} as Record<string,string>)[text(a.kind)]||text(a.kind)}</span><b>{a.kind==='production'&&dominant?`${text(dominant.name)}: ${number(dominant.area_m2)} m² alanı pilotta doğrula`:a.kind==="water"&&value(stored?.m3)>0?`%${number(stored?.share_pct,0)} depodan karşıla${value(sea?.m3)>0?`; ${waterLabel(sea?.m3)} arıtmayla tamamla`:""}`:text(a.title)}</b></summary><p>{text(a.text)}</p>{a.kind==='water'&&actions.filter(x=>x.id==='seasonal_backup').map(x=><p key={text(x.id)}>{text(x.title)}. {text(x.text)}</p>)}</details>)}</div>
}

export function WaterSecurity({story}:{story:JsonRecord}){
  const w=obj(story.water_security),sources=list(w.sources),storage=obj(w.storage),critical=obj(w.critical_month),backup=obj(w.backup),dry=obj(w.dry_year_sensitivity)
  if(!Object.keys(w).length)return null
  return <div className="north-water-security"><div className="north-source-percent">{sources.filter(s=>value(s.m3)>0).map(s=><span key={text(s.id)}>{text(s.label)} <b>%{number(s.share_pct,1)}</b></span>)}</div><div className="north-water-indicators"><span>En çok yedek su isteyen ay<b>{text(critical.label)||'—'}</b></span><span>Seçilen depo<b>{number(storage.configured_m3)} m³</b></span><span>En zor model-yıl<b>{number(obj(backup.annual_m3).max)} m³ yedek</b></span></div><details><summary>Günlük su güvenliği · {backup.worst_year_is_first_modeled_year?'ilk işletme yılına dikkat':dry.is_sensitive===true?'değişkenliğe duyarlı':dry.is_sensitive===false?'sınanan koşullarda sınırlı değişim':'sınama yapılmadı'}</summary><p>Depo hacmi tasarım girdisidir; hesaplanmış asgari kapasite değildir. Günlük hesapta en yüksek doluluk {number(storage.modeled_peak_occupied_m3)} m³. Kritik ay, modellerin günlük hesabından elde edilen aylık ortalamalar içindeki en yüksek yedek su ihtiyacıdır; tek bir kurak yılın ayı değildir.</p>{backup.worst_year_is_first_modeled_year===true&&<p><b>En yüksek yedek gereği ilk model yılında oluştu.</b> Depo boş başlatıldığı için bu sonuç ilk işletme koşulunu da içerir; tek başına kuraklık kanıtı değildir.</p>}<p>En yüksek günlük yedek gereği {number(typeof backup.maximum_daily_m3==="number"?backup.maximum_daily_m3*1000:null)} litre. En zor model-yıl farkı %{number(dry.increase_pct)}; sınıflama eşiği %{number(dry.display_threshold_pct)}. Bu bir olasılık tahmini değildir.</p></details></div>
}

export function FieldChips(){return <div className="north-field-chips"><span><Icon name="sensor" size={13}/><b>PWN</b> Su sıcaklığı / tuzluluk profili</span><span><Icon name="sample" size={13}/><b>NUMUNE</b> Kaynak suyu kimyası · izinle</span><span><Icon name="source" size={13}/><b>DİĞER ARAŞTIRMA</b> Karasal su / zemin / enerji</span></div>}
