import type {JsonRecord} from '../api'
import {obj,list,number} from '../ui'
const n=(v:unknown)=>typeof v==='number'?v:0
const names:Record<string,string>={lighting_kwh_m2:'Bitki ışıkları',pumping_kwh_m2:'Su dolaşımı',fans_kwh_m2:'Havalandırma',dehumidification_kwh_m2:'Nem alma',cooling_kwh_m2:'Soğutma'}
export function StorageDesign({result}:{result:JsonRecord}){
 const water=obj(obj(result.infrastructure).water),minimum=water.minimum_for_all_tested_records_m3
 if(!Object.keys(water).length||water.classification==='NOT_APPLICABLE')return null
 return <section><h3>Bu üretim için nasıl bir depo ve yedek gerekir?</h3><div className="north-range-row"><span>Seçilen depo<b>{number(water.selected_capacity_m3)} m³</b></span><span>Yağış/kar ile çalışma için hesaplanan depo<b>{typeof minimum==='number'?`${number(minimum)} m³`:'Depoyu büyütmek tek başına yetmez'}</b><small>Sınanan kayıtların tamamı · ilk dolum hariç</small></span><span>Seçilen depoyla yoğun gündeki yedek<b>{number(n(water.backup_peak_m3_day)*1000)} litre/gün</b></span></div><p>{typeof minimum==='number'?n(water.selected_capacity_m3)>=minimum?'Seçilen depo, sınanan kayıtların döngüsel işletiminde yeterli görünüyor; ilk dolumu ve su kalitesini ayrıca doğrula.':`Bu üretimi yağış/karla sürdürmek için depoyu yaklaşık ${number(minimum)} m³ düzeyinde araştır veya yedek kaynağı koru.`:'Bazı kayıtlarda toplam toplama üretim ihtiyacından az. Daha büyük depo su yaratmaz; toplama alanını, üretimi veya yedek kaynağı birlikte değiştir.'}</p><details><summary>Toplanabilen su azalırsa ne olur?</summary><table><thead><tr><th>İklim kaydı</th><th>Toplama</th><th>Yıllık ort. yedek</th><th>Aralıksız yedek</th></tr></thead><tbody>{list(water.models).flatMap(m=>list(m.scenarios).map(r=><tr key={`${m.model}-${r.capture_factor}`}><td>{String(m.model)}</td><td>%{number(n(r.capture_factor)*100,0)}</td><td>{number(r.backup_mean_m3_year)} m³</td><td>{number(r.longest_backup_run_days,0)} gün</td></tr>))}</tbody></table><p>%75/%50 toplama bir stres testidir; olayın gerçekleşme olasılığı değildir. Ürün planı sabit tutularak yalnız su sistemi sınanır.</p></details><details><summary>Hesabın sınırları</summary>{(water.assumptions as string[]||[]).map(x=><p key={x}>{x}</p>)}</details></section>
}
export function SupplyDesign({result}:{result:JsonRecord}){
 const energy=obj(obj(result.infrastructure).energy),parts=obj(energy.components_kwh_year),values=Object.values(parts).map(n),max=Math.max(1,...values)
 if(!Object.keys(energy).length||energy.classification==='NOT_APPLICABLE')return null
 return <section><h3>Enerji nerede kullanılıyor?</h3><div className="north-energy-bars">{Object.entries(parts).map(([key,value])=><div key={key}><span>{names[key]||key}</span><i style={{width:`${n(value)/max*60}%`,background:'#bc913d'}}/><b>{number(value,0)} kWh/yıl</b></div>)}</div><div className="north-range-row"><span>En yoğun işletme ayı<b>{['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'][n(energy.busiest_month)-1]}</b></span><span>Üretim işletimi için güç taraması<b>{number(energy.operation_power_upper_bound_kw)} kW</b><small>Isı + elektrik azamileri toplamı</small></span><span>Enerji bağlantısı<b>{energy.power_screen_status==='UNCONFIRMED'?'Yerelde doğrulanacak':energy.power_screen_status==='DESIGN_REVIEW'?'Beyan edilen gücü aşabilir':'İşletim hesabı sınırın içinde'}</b><small>Arıtma gücü ve ilk çalıştırma ayrıca</small></span></div><div className="north-monthly">{(energy.monthly_operation_kwh as number[]||[]).map((v,i)=><div key={i} title={`${i+1}. ay ${number(v,0)} kWh`}><div><i style={{height:`${v/Math.max(1,...energy.monthly_operation_kwh as number[])*100}%`,background:'#bd964a'}}/></div><span>{i+1}</span></div>)}</div><p>Yıllık kWh, toplam tüketimdir. kW ise aynı anda gereken güçtür. Yıllık enerji yeterli olsa bile yoğun anda bağlantı yetersiz kalabilir.</p><details><summary>Güç ve enerji hesabının sınırları</summary>{(energy.limits as string[]||[]).map(x=><p key={x}>{x}</p>)}</details></section>
}
