import TurkeyOutcome from './TurkeyOutcome'
import TurkeyAnalysisExplorer from './TurkeyAnalysisExplorer'
import TurkeyEconomics from './TurkeyEconomics'
import type { JsonRecord } from '../api'
import type { PlanningContext, SimulationRequest, SimulationResult } from '../planning'
import { methodName, sourceName } from '../planning'
import { Badge, Card, Empty, Metric, SourceLink, list, number, obj, str } from '../ui'

type BarRow={id:string;name:string;before:number|null;after:number|null}
const finite=(v:unknown):number|null=>typeof v==='number'&&Number.isFinite(v)?v:null
const compact=(v:number)=>new Intl.NumberFormat('tr-TR',{notation:'compact',maximumFractionDigits:1}).format(v)
const palette={before:'#829aa1',after:'#248777',target:'#c68937'}
function PairedChart({rows,unit,label,before='Mevcut desen',after='Hesaplanan desen',target}:{rows:BarRow[];unit:string;label:string;before?:string;after?:string;target?:number}){
  const maximum=Math.max(target||0,...rows.flatMap(r=>[r.before||0,r.after||0]),1),left=170,width=410,height=rows.length*66+48
  return <><div className="analysis-chart-legend"><span><i style={{background:palette.before}}/>{before}</span><span><i style={{background:palette.after}}/>{after}</span>{target!==undefined&&<span><i style={{background:palette.target}}/>Ürün hedefi: %{target}</span>}</div><svg className="analysis-chart" viewBox={`0 0 720 ${height}`} role="img" aria-label={label} style={{width:'100%',height:'auto',display:'block'}}><title>{label}</title>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1={left+width*f} y1={18} x2={left+width*f} y2={height-25} stroke="currentColor" opacity={.09}/><text x={left+width*f} y={height-6} textAnchor="middle" fontSize={10} fill="currentColor">{compact(maximum*f)}</text></g>)}{target!==undefined&&<line x1={left+width*target/maximum} y1={18} x2={left+width*target/maximum} y2={height-25} stroke={palette.target} strokeDasharray="4 4"/>}{rows.map((r,i)=><g key={r.id}><text x={4} y={i*66+35} fontSize={12} fill="currentColor">{r.name}</text>{([{v:r.before,color:palette.before,name:before},{v:r.after,color:palette.after,name:after}]).map((s,j)=><g key={j}><rect x={left} y={i*66+17+j*20} width={s.v===null?0:Math.max(0,width*s.v/maximum)} height={13} rx={3} fill={s.color}><title>{r.name} · {s.name}: {s.v===null?'Bilinmiyor / hesaplanmadı':`${number(s.v,2)} ${unit}`}</title></rect><text x={left+width+10} y={i*66+28+j*20} fontSize={11} fill="currentColor">{s.v===null?'—':compact(s.v)} {s.v===null?'':unit}</text></g>)}</g>)}</svg><p className="small muted">—: veri eksik veya uygulanabilir sonuç yok. Sıfır değerleri sıfır olarak gösterilir.</p></>
}

function MonthlyClimate({context}:{context:JsonRecord|null}){
  const months=list(context?.monthly).filter(m=>finite(m.month)!==null&&finite(m.tmin_c)!==null&&finite(m.tmax_c)!==null&&finite(m.precipitation_mm)!==null).sort((a,b)=>Number(a.month)-Number(b.month))
  if(!months.length)return null
  const low=Math.floor(Math.min(0,...months.map(m=>Number(m.tmin_c)))/5)*5,high=Math.ceil(Math.max(5,...months.map(m=>Number(m.tmax_c)))/5)*5,precipMax=Math.max(1,...months.map(m=>Number(m.precipitation_mm)))
  const x=(month:number)=>58+(month-1)*49,y=(temp:number)=>185-(temp-low)/(high-low)*160
  const line=(key:string)=>months.map(m=>`${x(Number(m.month))},${y(Number(m[key]))}`).join(' ')
  return <Card title="Aylık iklim profili · seçili kaynak verisi"><p className="small muted">{str(context?.model)} · {str(context?.scenario)} · {str(obj(context?.future).period)}. Aylık özetler kaynaklı günlük seriden türetilir.</p><div className="two-columns"><div><h3>Hava sıcaklığı · °C</h3><svg className="analysis-chart" role="img" aria-label="Aylık ortalama günlük minimum ve maksimum sıcaklıklar, derece Celsius" viewBox="0 0 640 225" style={{width:'100%',height:'auto'}}><title>Aylık ortalama günlük Tmin ve Tmax · °C</title>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1={45} x2={615} y1={y(low+f*(high-low))} y2={y(low+f*(high-low))} stroke="currentColor" opacity={.12}/><text x={38} y={y(low+f*(high-low))+4} textAnchor="end" fontSize={11} fill="currentColor">{number(low+f*(high-low),1)}</text></g>)}<polyline points={line('tmin_c')} fill="none" stroke="#68a9b8" strokeWidth={3}/><polyline points={line('tmax_c')} fill="none" stroke="#c68937" strokeWidth={3}/>{months.map(m=><g key={String(m.month)}><text x={x(Number(m.month))} y={207} textAnchor="middle" fontSize={11} fill="currentColor">{String(m.month)}</text><circle cx={x(Number(m.month))} cy={y(Number(m.tmin_c))} r={3} fill="#68a9b8"><title>{String(m.month)}. ay Tmin: {number(m.tmin_c,2)} °C</title></circle><circle cx={x(Number(m.month))} cy={y(Number(m.tmax_c))} r={3} fill="#c68937"><title>{String(m.month)}. ay Tmax: {number(m.tmax_c,2)} °C</title></circle></g>)}</svg><p className="small muted">Mavi: ortalama Tmin · sarı: ortalama Tmax · yatay eksen: ay</p></div><div><h3>Aylık toplam yağış · mm</h3><svg className="analysis-chart" role="img" aria-label="Aylık toplam yağış, milimetre" viewBox="0 0 640 225" style={{width:'100%',height:'auto'}}><title>Aylık toplam yağış · mm</title>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1={45} x2={615} y1={185-160*f} y2={185-160*f} stroke="currentColor" opacity={.12}/><text x={38} y={189-160*f} textAnchor="end" fontSize={11} fill="currentColor">{number(precipMax*f,0)}</text></g>)}{months.map(m=><g key={String(m.month)}><rect x={x(Number(m.month))-14} y={185-160*Number(m.precipitation_mm)/precipMax} width={28} height={160*Number(m.precipitation_mm)/precipMax} rx={3} fill="#248777"><title>{String(m.month)}. ay: {number(m.precipitation_mm,2)} mm</title></rect><text x={x(Number(m.month))} y={207} textAnchor="middle" fontSize={11} fill="currentColor">{String(m.month)}</text></g>)}</svg><p className="small muted">Yağış, kullanılabilir su tahsisi değildir · yatay eksen: ay</p></div></div><details><summary>Aylık sayısal değerleri incele</summary><div className="table-scroll"><table><thead><tr><th>Ay</th><th>Ort. Tmin · °C</th><th>Ort. Tmax · °C</th><th>Toplam yağış · mm</th></tr></thead><tbody>{months.map(m=><tr key={String(m.month)}><th>{String(m.month)}</th><td>{number(m.tmin_c,2)}</td><td>{number(m.tmax_c,2)}</td><td>{number(m.precipitation_mm,2)}</td></tr>)}</tbody></table></div></details></Card>
}

export default function AnalysisData({context,scenario,result,northContext}:{context:PlanningContext;scenario:SimulationRequest;result:SimulationResult|null;northContext:JsonRecord|null}){
  const run=result?.request||scenario,north=scenario.mode==='north',optimized=result?.optimized
  const name=(id:string)=>str(context.crop_catalog.find(c=>c.crop_id===id)?.name_tr)||id
  const baseline=list(context.region.crops),sources=list(context.region.sources)
  const waterRows:BarRow[]=run.crops.map(c=>({id:c.crop_id,name:name(c.crop_id),before:finite(result?.current.crops.find(r=>r.crop_id===c.crop_id)?.water_m3),after:optimized?optimized.allocations.filter(a=>a.crop_id===c.crop_id).reduce((s,a)=>s+a.water_m3,0):null}))
  const productionRows:BarRow[]=run.crops.map(c=>{const current=finite(result?.current.crops.find(r=>r.crop_id===c.crop_id)?.production_kg),next=finite(optimized?.crops.find(r=>r.crop_id===c.crop_id)?.production_kg);return {id:c.crop_id,name:name(c.crop_id),before:current===null?null:100*current/c.target_production_kg,after:next===null?null:100*next/c.target_production_kg}})
  const budget=result?finite(result.current.totals.available_water_m3):scenario.water_sources.filter(s=>s.enabled&&s.quality_suitable===true).reduce((sum,s)=>sum+s.capacity_m3,0)
  const climateBase=obj(northContext?.baseline),climateFuture=obj(northContext?.future)
  const allocations=optimized?.allocations||[]
  const methods=(['open_field','greenhouse','hydroponics'] as const).filter(m=>allocations.some(a=>a.method===m))
  const sourceIds=run.water_sources.map(s=>s.source_id)
  const sourceColors=['#248777','#68a9b8','#c68937','#6f75a7']
  const methodMax=Math.max(1,...methods.map(m=>allocations.filter(a=>a.method===m).reduce((s,a)=>s+a.water_m3,0)))
  if(!north)return <div className="turkey-analysis">{result?.optimized?<><TurkeyOutcome context={context} result={result}/><TurkeyEconomics key={result.request.region_id} result={result}/><TurkeyAnalysisExplorer context={context} result={result}/></>:<Empty>Grafikler için simülasyonu çalıştırın.</Empty>}<details className="result-audit"><summary>Kaynak veriler / ham tablolar</summary><div className="table-scroll"><table><thead><tr><th>Ürün</th><th>Alan · ha</th><th>Üretim · ton</th><th>Verim · kg/ha</th></tr></thead><tbody>{list(context.region.crops).map(c=><tr key={str(c.crop_id)}><th>{str(c.name_tr)}</th><td>{number(c.area_ha,1)}</td><td>{number(c.production_tonnes,0)}</td><td>{number(c.yield_kg_ha,1)}</td></tr>)}</tbody></table></div>{sources.map((s,i)=><p key={i}><SourceLink url={str(s.url)}>{str(s.title)}</SourceLink> · {String(s.data_year)}</p>)}</details></div>
  return <div className="analysis-data">
    <Card title="Girdiler, grafikler ve hesap dayanakları" action={<Badge kind={result?'SIMULATION_EXPLANATORY':'OFFICIAL_STATISTICS'}>{result?'Çalıştırma verisi':'Başlangıç ve senaryo girdileri'}</Badge>}><p className="small">{result?`Grafikler ${result.run_id} çalıştırmasının değişmez girdilerini kullanır. Paneldeki sonraki düzenlemeler yeni hesaplamaya kadar grafikleri değiştirmez.`:'Kaynaklı başlangıç ve senaryo girdilerini hesaplamadan önce inceleyebilirsiniz. Su / öneri grafikleri ilk hesaplamadan sonra açılır.'}</p>{north&&<p className="input-note">Kuzey çıktıları açıklayıcı, varsayıma dayalı hesaplamadır; doğrulanmış yerel gelecek üretim önerisi değildir.</p>}</Card>
    <div className="resource-hero"><Metric name="Mevcut desenin su gereği" value={result?.current.totals.water_m3} unit="m³"/><Metric name="Hesaplanan desenin su gereği" value={optimized?.totals.water_m3} unit="m³"/><Metric name="Uygun varsayılan su bütçesi" value={budget} unit="m³" foot="Kaynak kapasitesi; ölçülmüş yıllık tahsis değil."/><Metric name="Hesaplanan enerji gereği" value={optimized?.totals.energy_kwh} unit="kWh" foot="Bilinmeyen katsayılar sıfır sayılmaz."/></div>
    {result?<><Card title="Ürünlerin kaynak suyu gereği" action={<Badge kind="SIMULATION_EXPLANATORY"/>}><PairedChart rows={waterRows} unit="m³" label="Ürün bazında mevcut ve hesaplanan desenin brüt su gereği"/><div className="table-scroll"><table><thead><tr><th>Ürün</th><th>Mevcut su gereği · m³</th><th>Hesaplanan su gereği · m³</th></tr></thead><tbody>{waterRows.map(r=><tr key={r.id}><th>{r.name}</th><td>{number(r.before,2)}</td><td>{number(r.after,2)}</td></tr>)}</tbody></table></div><p className="input-note">Mevcut ve hesaplanan desen aynı çalıştırma koşullarındadır. Tarla için brüt sulama, kontrollü sistem için girilen kaynak suyu katsayısı kullanılır; yağış ve toplam ETc ile karıştırılmaz.</p></Card><Card title="Her ürün kendi üretim hedefine göre"><PairedChart rows={productionRows} unit="%" label="Her ürünün kendi kilogram hedefine göre mevcut ve hesaplanan üretim oranları" target={100}/><div className="table-scroll"><table className="analysis-table"><thead><tr><th>Ürün</th><th>Mevcut üretim · kg</th><th>Hedef · kg</th><th>Asgari · kg</th><th>Hesaplanan · kg</th><th>Hedef önceliği</th></tr></thead><tbody>{run.crops.map(c=><tr key={c.crop_id}><th>{name(c.crop_id)}</th><td>{number(result.current.crops.find(x=>x.crop_id===c.crop_id)?.production_kg)}</td><td>{number(c.target_production_kg)}</td><td>{number(c.min_production_kg)}</td><td>{number(optimized?.crops.find(x=>x.crop_id===c.crop_id)?.production_kg)}</td><td>{number(c.priority,2)}</td></tr>)}</tbody></table></div><p className="input-note">%100 her ürünün kendi hedefidir. Farklı ürünlerin kg değerleri toplanarak beslenme veya ekonomik değer iddiası üretilmez. Grafik %100 üzerindeki üretimi gizlemez.</p></Card><Card title="Su gereği ve erişilebilir bütçe"><PairedChart rows={[{id:'current',name:'Mevcut desen',before:finite(result.current.totals.water_m3),after:budget},{id:'optimized',name:'Hesaplanan desen',before:finite(optimized?.totals.water_m3),after:budget}]} unit="m³" label="Mevcut ve hesaplanan toplam su gereğinin uygun varsayılan kaynak bütçesiyle karşılaştırılması" before="Su gereği" after="Uygun varsayılan bütçe"/><p className="input-note">Yalnız etkin ve kalite uygunluğu kabul edilmiş kaynak kapasiteleri bütçeye girer. Su azalması; üretim ve atanmayan alanla birlikte okunmalıdır.</p></Card></>:<Card title="Karşılaştırma grafikleri"><Empty>Senaryo Lab içinden hesaplamayı çalıştırın. Mevcut / hesaplanan su ve ürün bazında üretim karşılaştırması burada açılacak.</Empty></Card>}
    {north&&<Card title="Yöntem × su kaynağı tahsisi">{optimized&&methods.length?<><div className="analysis-chart-legend">{sourceIds.map((s,i)=><span key={s}><i style={{background:sourceColors[i%sourceColors.length]}}/>{sourceName[s]}</span>)}</div><svg className="analysis-chart" role="img" aria-label="Üretim yöntemlerinin su kaynaklarına göre tahsisi, bütün çubuklar metreküp biriminde" viewBox={`0 0 720 ${methods.length*52+36}`} style={{width:'100%',height:'auto',display:'block'}}><title>Yöntemlere tahsis edilen kaynak suyu · m³</title>{methods.map((method,i)=>{let offset=0;const total=allocations.filter(a=>a.method===method).reduce((s,a)=>s+a.water_m3,0);return <g key={method}><text x={4} y={i*52+29} fontSize={12} fill="currentColor">{methodName[method]}</text>{sourceIds.map((source,j)=>{const value=allocations.filter(a=>a.method===method&&a.water_source===source).reduce((s,a)=>s+a.water_m3,0),x=170+410*offset/methodMax;offset+=value;return <rect key={source} x={x} y={i*52+12} width={410*value/methodMax} height={24} fill={sourceColors[j%sourceColors.length]}><title>{methodName[method]} · {sourceName[source]}: {number(value,2)} m³</title></rect>})}<text x={590} y={i*52+29} fontSize={11} fill="currentColor">{number(total,1)} m³</text></g>})}</svg><div className="table-scroll"><table><thead><tr><th>Ürün / yöntem</th><th>Kapasite</th><th>Kaynak</th><th>Su · m³</th><th>Enerji · kWh</th><th>Sezon</th></tr></thead><tbody>{allocations.map((a,i)=><tr key={i}><th>{a.name_tr}<small>{methodName[a.method]}</small></th><td>{number(a.capacity_used,2)} {a.capacity_unit==='m2'?'m²':a.capacity_unit}</td><td>{sourceName[a.water_source]||a.water_source}</td><td>{number(a.water_m3,2)}</td><td>{number(a.energy_kwh,2)}</td><td>{a.season_start}<small>{a.season_end}</small></td></tr>)}</tbody></table></div><p className="input-note">Grafik yalnız su hacimlerini toplar. Açık tarla ha ve kontrollü yüzey m² tabloda ayrı birimleriyle gösterilir; tek alan büyüklüğüne dönüştürülmez.</p></>:<Empty>{result?'Bu çalıştırmada uygulanabilir yöntem / kaynak tahsisi yok.':'Yöntem / kaynak tahsisi ilk uygulanabilir hesaplamada görünür.'}</Empty>}</Card>}
    <Card title="Su hesabının girdileri ve dönüşümleri" className="analysis-evidence"><div className="table-scroll"><table><thead><tr><th>Ürün</th><th>ETc · mm</th><th>Net sulama · mm</th><th>Brüt su · m³/ha</th><th>Kaynak / durum</th></tr></thead><tbody>{(result?.crop_water||scenario.crops.map((c):JsonRecord=>({crop_id:c.crop_id,etc_mm:null,net_irrigation_mm:c.manual_net_irrigation_mm,gross_water_m3_ha:null,source:c.manual_net_irrigation_mm===null?'Hesaplama bekleniyor':'USER_SCENARIO',reason:'Brüt su ilk hesaplamada gösterilir.'}))).map((c,i)=><tr key={i}><th>{name(str(c.crop_id))}</th><td>{number(c.etc_mm,2)}</td><td>{number(c.net_irrigation_mm,2)}</td><td>{number(c.gross_water_m3_ha,2)}</td><td>{str(c.source)||str(c.classification)||str(c.status)}<small>{str(c.reason)}</small></td></tr>)}</tbody></table></div><p className="small muted">1 mm × 1 ha = 10 m³. Brüt gereksinim = net sulama × 10 / sulama verimi. Çalıştırma verimi: {number(run.irrigation_efficiency*100)}%. ETc, net sulama ve brüt kaynak suyu farklı büyüklüklerdir. Elle net sulama, eksik ETc verisi gibi gösterilmez.</p></Card>
    <Card title={north?'Kuzey aday portföyünün başlangıç parametreleri':'Resmî başlangıç ürün verisi'}><div className="table-scroll"><table><thead><tr><th>Ürün</th><th>Kaynak alan · ha</th><th>Kaynak üretim · ton</th><th>Kaynak verim · kg/ha</th><th>Senaryo alan · ha</th><th>Senaryo verim · kg/ha</th></tr></thead><tbody>{scenario.crops.map(c=>{const b=baseline.find(x=>x.crop_id===c.crop_id);return <tr key={c.crop_id}><th>{name(c.crop_id)}</th><td>{number(b?.area_ha,2)}</td><td>{number(b?.production_tonnes,2)}</td><td>{number(b?.yield_kg_ha,2)}</td><td>{number(c.current_area_ha,2)}</td><td>{number(c.yield_kg_ha,2)}</td></tr>})}</tbody></table></div><p className="input-note">{north?'Kuzey adayları için resmî yerel ekiliş / verim başlangıcı yoktur; boş kaynak hücreleri sıfır demek değildir. Senaryo verimleri yerel gözlem değildir.':'Kaynak değerler il düzeyinde seçili ürün istatistikleridir; havzanın tamamı veya tekil fiziksel arazi değildir. Kaynak verim = üretim ton × 1000 / ekiliş ha. Senaryo sütunları güncel düzenlemeleri gösterir.'}</p><div className="analysis-sources">{sources.map((s,i)=><p key={i} className="small"><SourceLink url={str(s.url)}>{str(s.title)||str(s.id)}</SourceLink> · veri yılı {String(s.data_year||context.region.year||'—')} · sayfa {String(s.page||'—')}</p>)}</div></Card>
    {north&&<Card title="Gelecek iklim verisi · üretim sonucundan ayrı"><div className="table-scroll"><table><thead><tr><th>Gösterge</th><th>{str(climateBase.period)||'Referans dönem'}</th><th>{str(climateFuture.period)||'Gelecek dönem'}</th></tr></thead><tbody>{[{key:'mean_annual_gdd5_degree_days',label:'GDD · taban 5 °C · derece-gün'},{key:'mean_annual_frost_free_run_days',label:'Don olmayan kesintisiz süre · gün'},{key:'mean_annual_precipitation_mm',label:'Yağış · mm/yıl'}].map(row=><tr key={row.key}><th>{row.label}</th><td>{number(climateBase[row.key],2)}</td><td>{number(climateFuture[row.key],2)}</td></tr>)}</tbody></table></div><p className="input-note">{str(northContext?.model)||'EC_Earth3P_HR'} · {str(northContext?.scenario)||'tek model bağlamı'}. Tek yıllık SSP çıktısı uzun dönem klimatoloji değildir. Bu tablo ürünün yerel uygunluğunu veya yıllık kullanılabilir su tahsisini doğrulamaz. Gelecek ET₀ / kara hidrolojisi bağlantısı henüz eksiktir.</p></Card>}
    {north&&<MonthlyClimate context={northContext}/>}
  </div>
}


