import TurkeyOutcome from './TurkeyOutcome'
import TurkeyDecisionCanvas from './TurkeyDecisionCanvas'
import CurrentWeather from './CurrentWeather'
import type { PlanningContext, SimulationRequest, SimulationResult } from '../planning'
import { methodName, sourceName } from '../planning'
import type { JsonRecord } from '../api'
import { Icon, number, str, obj, list, Download } from '../ui'
import SimulationResults from './SimulationResults'

type Props={context:PlanningContext;scenario:SimulationRequest;result:SimulationResult|null;automatic:JsonRecord|null;onResearch:()=>void;stale?:boolean}
function Meter({label,used,capacity,unit,tone,binding=false}:{label:string;used:unknown;capacity:unknown;unit:string;tone:string;binding?:boolean}){
  const valid=typeof used==='number'&&typeof capacity==='number',ratio=valid&&Number(capacity)>0?Math.min(100,Number(used)/Number(capacity)*100):0
  return <div className={`resource-meter ${tone} ${binding?'binding':''}`}><div><Icon name={tone} size={16}/><span>{label}</span>{binding&&<small>{tone==='water'?'KAYNAK SINIRI':'SINIRDA'}</small>}</div><strong>{number(used,unit==='ha'?2:0)} <small>/ {number(capacity,0)} {unit}</small></strong><div className="meter-track"><i style={{width:`${ratio}%`}}/></div><p>{valid?Number(used)>Number(capacity)?`${number(Number(used)-Number(capacity),0)} ${unit} AÇIK`:`${number(Number(capacity)-Number(used),unit==='ha'?2:0)} ${unit} kalan`:'DATA NEEDED'}</p></div>
}
export default function DecisionCanvas({context,scenario:q,result,automatic,onResearch,stale=false}:Props){
  const partial=!!result?.regional_scope
  const north=q.mode==='north',plan=result?.optimized,current=result?.current||context.baseline_analysis.current
  const maxArea=Math.max(1,...current.crops.map(c=>c.area_ha),...(plan?.crops.map(c=>c.area_ha)||[]))
  const binding=result?.constraints.filter(c=>c.binding&&c.capacity>0)||[]
  const amounts=plan?.totals
  const waterBudget=q.water_sources.filter(s=>s.enabled&&s.quality_suitable===true).reduce((t,s)=>t+s.capacity_m3,0)
  const cropRows=north?q.crops.map(c=>({id:c.crop_id,name:str(context.crop_catalog.find(k=>k.crop_id===c.crop_id)?.name_tr),current:0})):current.crops.map(c=>({id:c.crop_id,name:c.name_tr,current:c.area_ha}))
  if(!north)return <TurkeyDecisionCanvas context={context} scenario={q} result={result} stale={stale}/>
  return <div className="decision-instrument">
    <div className="decision-heading"><div><span className="instrument-eyebrow">{north?'PRE-TASE · ÜRETİM SİSTEMİ':'BÖLGESEL ÜRETİM KARARI'}</span><h1>{north?'Geleceğin üretim deseni':'Mevcut desen → önerilen desen'}</h1></div><span className={`decision-state ${plan?'ready':''}`}>{plan?(partial?'KISMİ ÖNERİ':'HESAPLANAN ÖNERİ'):result?.status==='infeasible'?'KISITLAR SAĞLANMIYOR':north?'DATA NEEDED':'KAYNAKLI MEVCUT DESEN'}</span></div>
    <p className="decision-intro">{north?(plan?'Ürün miktarları aynı matematiksel motorla hesaplandı. Yerel olarak doğrulanmamış katsayılar açık varsayımdır.':'Kaynaklı iklim ve adaylar hazır. Yerel üretim girdileri tamamlanmadan miktar önerisi verilmiyor.'):`${String(context.region.year)} resmî il deseni (seçili ürünler). Öneri: üretim alt sınırlarında ekili alanı koruyan, sonra suyu azaltan model hesabı.`}</p>
    {!north&&<CurrentWeather key={q.region_id} region={q.region_id}/>}

    {partial&&<div className="partial-plan-note"><b>Kısmi öneri · toplam su DATA NEEDED</b><p>{result?.regional_scope?.note}</p></div>}
    <div className="instrument-pattern" aria-label="Üretim deseni"><div className="pattern-legend"><span><Icon name="seed" size={15}/> ÜRÜN / YÖNTEM</span><span>{north?'HESAPLANAN ÜRETİM / KAPASİTE':<><i className="legend-current"/> Mevcut <i className="legend-recommended"/> Önerilen</>}</span></div>
      {cropRows.map(c=>{const recommendation=plan?.crops.find(r=>r.crop_id===c.id),allocations=plan?.allocations.filter(a=>a.crop_id===c.id)||[],screen=list(automatic?.candidate_analysis).find(s=>s.crop_id===c.id),screened=obj(screen?.thermal_screen).status==='screened_out';return <article className={`decision-crop ${north?'northern':''}`} key={c.id}><div className="decision-crop-name"><Icon name={allocations.some(a=>a.method!=='open_field')?'greenhouse':'seed'} size={18}/><strong>{c.name}</strong><small>{north?(allocations.length?[...new Set(allocations.map(a=>methodName[a.method]))].join(' + '):screened?'Tarla: ön taramada elendi':'Araştırma adayı'):recommendation?.held_for_missing_water?'Sabit · su verisi eksik':'Açık tarla'}</small></div>{north?<div className="northern-output"><strong>{recommendation?number(recommendation.production_kg,0):'—'} <small>kg</small></strong><span>{allocations.length?Object.entries(allocations.reduce((acc,a)=>({...acc,[a.capacity_unit]:(acc[a.capacity_unit]||0)+a.capacity_used}),{} as Record<string,number>)).map(([u,n])=>`${number(n,2)} ${u==='m2'?'m²':u}`).join(' + '):plan?'Kapasite ayrılmadı':'DATA NEEDED'}</span></div>:<><div className="crop-bar-pair" role="img" aria-label={`${c.name}: mevcut ${number(c.current)} ha, önerilen ${number(recommendation?.area_ha)} ha`}><i style={{width:`${c.current/maxArea*100}%`}}/><i className="recommended" style={{width:`${(recommendation?.area_ha||0)/maxArea*100}%`}}/></div><div className="crop-amount"><span>{number(c.current,0)}</span><b>→ {number(recommendation?.area_ha,0)}</b><small>ha</small></div></>}
      {recommendation&&<div className="crop-decision-detail">{north?<><span>{allocations.map(a=>sourceName[a.water_source]).filter((s,i,a)=>a.indexOf(s)===i).join(' · ')||'Kullanılan su kaynağı yok'}</span><span>{allocations[0]?`${allocations[0].season_start} → ${allocations[0].season_end}`:'—'}</span></>:<><span>Pay: %{number(c.current/q.land_area_ha*100,1)} → %{number(recommendation.area_share_pct,1)}</span><span>Üretim: {number(current.crops.find(x=>x.crop_id===c.id)?.production_kg,0)} → {number(recommendation.production_kg,0)} kg</span></>}<span>Su: {recommendation.held_for_missing_water?'DATA NEEDED':`${number(allocations.reduce((t,a)=>t+a.water_m3,0),0)} m³`}</span></div>}</article>})}
    </div>
    {!north&&result?.optimized&&<TurkeyOutcome context={context} result={result}/>}
    <div className="resource-strip"><Meter label={partial?"Bilinen ürünlerde su":"Önerilen desenin su gereği"} used={partial?amounts?.known_water_m3:amounts?.water_m3} capacity={waterBudget} unit="m³" tone="water" binding={binding.some(c=>c.id.startsWith('water_'))}/>{north?<Meter label="Enerji" used={amounts?.energy_kwh} capacity={q.energy_budget_kwh} unit="kWh" tone="energy" binding={binding.some(c=>c.id==='energy')}/>:<Meter label={partial?"Mevcut: bilinen ürünler":"Mevcut desenin su gereği"} used={partial?current.totals.known_water_m3:current.totals.water_m3} capacity={waterBudget} unit="m³" tone="water"/>}<Meter label="Açık alan" used={amounts?.open_field_area_ha} capacity={q.land_area_ha} unit="ha" tone="soil" binding={binding.some(c=>c.id==='land')}/></div>
    {plan&&<section className="decision-explanation"><h2>Neden bu desen?</h2><p>{str(result?.objective?.label)} · {north?str(result?.objective?.quantity_basis)==='capacity'?'Miktarlar kaynak kapasitesinden hesaplandı.':'Tanımlı talep sepeti kullanıldı.':'Üretim tabanları korundu; mevcut üretim miktarı tavan yapılmadı.'}</p>{!north&&<p className="water-comparison">{partial?'Bilinen ürünlerin ':''}Modellenmiş su farkı: {number((partial?current.totals.known_water_m3:current.totals.water_m3)!-(partial?amounts?.known_water_m3:amounts?.water_m3)!,0)} m³ · Atanmayan alan: {number(amounts?.unallocated_land_ha,1)} ha. Üretim değişimleri yukarıda ürün bazında gösterilir.</p>}<ul>{plan.crops.filter(c=>north?c.production_kg>0:Math.abs(c.delta_area_ha)>1).slice(0,3).map(c=><li key={c.crop_id}><b>{c.name_tr}:</b> {c.summary_reason}</li>)}</ul><div className="constraint-chips">{binding.slice(0,5).map(c=><span key={c.id} className={c.id.startsWith('water_')?'water':c.id==='energy'?'energy':'soil'}>{c.label} · {number(c.used,0)} {c.unit}</span>)}</div></section>}
    {result&&!plan&&<section className="decision-explanation"><h2>Hesabı ne durduruyor?</h2><ul>{[...new Set(result.excluded_options.map(o=>str(o.reason)))].slice(0,4).map(reason=><li key={reason}>{reason}</li>)}</ul>{result.status==='infeasible'&&<p>İzin verilen yöntemler ve kaynaklar üretim / alan alt sınırlarını birlikte karşılayamıyor. Ayrıntılı kısıt kaydı aşağıda; sınırlar otomatik gevşetilmedi.</p>}</section>}
    {north&&plan&&<section className="source-allocation"><h2>Su kaynakları → üretim</h2>{plan.water_sources.filter(s=>s.used_m3>0).map(s=><div key={s.source_id}><span>{sourceName[s.source_id]}</span><div><i style={{width:`${s.share_pct}%`}}/></div><b>{number(s.used_m3,1)} m³</b></div>)}</section>}
    <section className="decision-evidence"><div><Icon name="source"/><h2>Ne biliyoruz, ne eksik?</h2>{north&&<button className="button small" onClick={onResearch}><Icon name="sensor" size={15}/> TASE neyi test edebilir?</button>}</div>{north?<><div className="evidence-lines"><span><b>SOURCED</b> Günlük iklim · ürün literatürü</span><span><b>MODELED</b> İklim ön taraması · optimizasyon</span><span><b>ASSUMED</b> Kapasiteler · girilmiş üretim katsayıları</span><span><b>DATA NEEDED</b> Yerel hidroloji · zemin · verim · sera enerjisi</span></div><div className="water-chain">{['Su varlığı','Mevsim','Erişim / depo','Kalite','Arıtma / enerji','Üretim suyu'].map((label,i)=><span key={label}>{i>0&&<b>→</b>}{label}</span>)}</div><p>PWN ile sıcaklık / iletkenlik / derinlik ölçümü hedeflenir; yıllık karasal suyu ölçmez. Numune kimyası uzman ve laboratuvarla belirlenir.</p></>:<div className="evidence-lines"><span><b>SOURCED</b> Resmî il ürün alanları / üretim · ERA5</span><span><b>MODELED</b> FAO-56 su gereği · önerilen desen</span><span><b>ASSUMED</b> Su bütçesi · takvim · randıman / kısıtlar</span><span><b>DATA NEEDED</b> Gerçek su tahsisi · bağımsız saha doğrulaması</span></div>}</section>
    <details className="result-audit"><summary><Icon name="source" size={15}/> Hesap, ham tablolar ve kanıt kaydı {result&&<span>· {result.run_id.slice(0,10)}</span>}</summary>{result&&<Download data={result} filename={`plan-${result.run_id}.json`}/>}<SimulationResults context={context} scenario={q} result={result}/>{result?.input_resolution&&<pre>{JSON.stringify(result.input_resolution,null,2)}</pre>}</details>
  </div>
}
