import { useEffect, useState } from 'react'
import { api, type JsonRecord } from '../api'
import type { PlanningSession } from '../planning'
import { Card, Notice, Badge, number, obj, list, str, Download } from '../ui'

export default function ResearchMission({session,onCompare}:{session:PlanningSession|null;onCompare:()=>void}){
  const [result,setResult]=useState<JsonRecord|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[analyzed,setAnalyzed]=useState('')
  const input=session?.submitted||session?.scenario,signature=JSON.stringify(input)
  async function analyze(){if(!input||input.mode!=='north')return;setBusy(true);setError('');try{setResult(await api.informationValue(input));setAnalyzed(signature)}catch(e){setError(e instanceof Error?e.message:'Duyarlılık hesabı tamamlanamadı')}finally{setBusy(false)}}
  useEffect(()=>{if(session?.result&&input?.mode==='north')void analyze()},[])
  if(!session||session.scenario.mode!=='north')return <Notice>Saha araştırması gelecek kuzey üretim kararıyla ilişkilidir. Önce Gelecek / Kuzey modunu seçin.</Notice>
  const stale=analyzed!==signature
  return <div className="research-mission"><div className="workspace-heading"><div><h1>Karardan saha araştırmasına</h1><p>Hangi belirsizlik deseni değiştiriyor; hangisini TASE ölçebilir?</p></div><Badge kind="PLANNED_ARCTIC_OBSERVATION">Henüz saha ölçümü yok</Badge></div>
    <div className="field-chain">Üretim kararı → belirsiz girdi → PWN / numune → kalite kontrolü → aynı motor → yeni desen</div>
    <div className="research-toolbar"><button className="button primary" disabled={busy} onClick={()=>void analyze()}>{busy?'Aynı motor farklı girdilerle çalışıyor…':'Kritik belirsizlikleri hesapla'}</button><button className="button" onClick={onCompare}>PRE / POST gözlem deneyi</button>{result&&<Download data={result} filename="karar-duyarliligi.json"/>}</div>
    <p className="small muted">{session.result?'Son hesaplanan senaryonun planlama amacı ve diğer girdileri sabit tutulur.':'Önce bir kuzey deseni hesaplayın veya mevcut girdilerin eksiklerini inceleyin.'} Su ve enerji ±%20 stres testi; sıcaklık 5–18°C arıtma ilişkisinin çalışma alanıdır, Arktik tahmini değildir.</p>
    {error&&<Notice warn>{error}</Notice>}{result&&stale&&<Notice warn>Son çalıştırma değişti; aşağıdaki analiz önceki hesaba ait. Duyarlılığı yeniden hesaplayın.</Notice>}
    {result&&<Card title="KARAR İÇİN KRİTİK BELİRSİZLİKLER"><div className="table-scroll"><table><thead><tr><th>Değişken / mevcut girdi</th><th>Hesaplanan karar etkisi</th><th>TASE doğrudan ölçebilir mi?</th></tr></thead><tbody>{list(result.parameters).map(row=><tr key={str(row.id)}><th>{str(row.label)}<small>{number(row.base)} {str(row.unit)}</small></th><td className="wrap-cell"><strong>{str(row.decision_impact)}</strong><small>{str(row.range_source)}</small><details><summary>Deney sonuçları / kaynak değişimi</summary>{list(row.trials).map((trial,i)=>{const d=obj(trial.difference),resources=obj(d.resource_delta);return <p key={i}>{number(trial.value)} {str(row.unit)} · {str(trial.status)}<br/>Su farkı: {number(resources.water_m3)} m³ · enerji farkı: {number(resources.energy_kwh)} kWh<br/>Desen: {d.pattern_changed?'değişti':'değişmedi'} · bağlayıcı kısıt: {d.binding_changed?'değişti':'değişmedi'}</p>})}</details></td><td className="wrap-cell">{row.measurable?'Evet / uygun protokolle':'Hayır'}<small>{str(row.method)}</small></td></tr>)}</tbody></table></div><p className="small muted">Bu deterministik duyarlılık taramasıdır; olasılık, ekonomik bilgi değeri veya kesin saha önceliği değildir. Taranan aralıkta değişim olmaması da sonuçtur. Kapasite/dengeli amaçta kaynak değiştikçe tek-ürün normalizasyonu da yeniden hesaplanır. Tuzluluk ve kimyanın sayısal etkisi henüz bilinmiyor.</p></Card>}
    <div className="research-packages"><Card title="A · Gerçek su kolonu"><p>İzinli atıştan önce model kaydını sabitle. İletkenlik/salinite, sıcaklık, basınç/derinlik, UTC ve konum profilini kalibrasyon metaverisiyle topla; mümkünse referans CTD ile karşılaştır.</p><Badge>PLAN · PWN Arctic v1</Badge></Card><Card title="B · Fiziksel numune"><p>İzinli standart derinlik, geçiş/gradient ve arka plan. İzotoplar kaynak izleme; sınırlı iyon/bor/alkalinite paneli kaynak ve arıtma uygunluğu için adaydır. Derinlikler ve analizler uzman/laboratuvar onayıyla seçilecek.</p><Badge>PROTOKOL GEREKLİ</Badge></Card><Card title="C · Karar bilgisi"><p>Yalnız gözlemin desteklediği girdiyi güncelle. Aynı motorla ürün, yöntem, su kaynağı, enerji ve kısıt farkını ölç. Değişmeyen karar ve modelle uyum geçerli sonuçtur.</p><button className="text-button" onClick={onCompare}>Açıklayıcı PRE / POST deneyini aç →</button></Card></div>
    <details><summary>Sefer sonrası kaynak suyu → kontrollü yetiştirme</summary><p className="small">İzinli numune veya ölçülen kimyadan yeniden oluşturulmuş sentetik su → uygun arıtma/koşullandırma → standart besin çözeltisi → kısa çevrimli kontrollü deney. Su, enerji, EC ve biyokütle/yield ölçümleri yöntemin varsayımlarını sınar; bütün Arktik ürün desenini doğrulamaz.</p></details>
  </div>
}
