const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
 const out=path.resolve('docs/verification'),report={verified_at:new Date().toISOString(),version:'0.5.1',checks:[],errors:[],http_errors:[],external_requests:[]};
 try{
 const context=await browser.newContext({viewport:{width:1366,height:768}});
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&!['localhost','127.0.0.1'].includes(u.hostname)){report.external_requests.push(u.href);return route.abort()}return route.continue()});
 const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.http_errors.push({url:r.url(),status:r.status()})});
 const check=(test,data={})=>{report.checks.push({test,passed:true,...data});console.log('PASS '+test)};
 const waitPost=()=>page.waitForResponse(r=>r.url().endsWith('/api/simulate')&&r.request().method()==='POST');
 const autoWait=id=>page.waitForResponse(r=>r.url().includes('/api/automatic-north')&&r.url().includes(id));
 const shot=async name=>{await page.evaluate(()=>{document.querySelector('.lab-scroll')?.scrollTo(0,0);document.querySelector('.analysis-canvas')?.scrollTo(0,0)});await page.screenshot({path:path.join(out,name)})};
 const baselineWait=waitPost(),contextWait=page.waitForResponse(r=>r.url().includes('/api/planning-context')&&r.url().includes('konya'));
 await page.goto('http://127.0.0.1:8000/#turkiye',{waitUntil:'networkidle'});const baseline=await(await baselineWait).json();const loadedContext=await(await contextWait).json();assert.equal(baseline.request.region_id,'konya');assert.equal(baseline.status,'conditional');assert.equal(baseline.optimized.crops.length,5);assert.equal(loadedContext.region.region_id||loadedContext.region.id,'konya');await page.getByText('Son hesap hazır',{exact:true}).waitFor();check('Konya automatically loads sourced context and calculates five-crop pattern before any user interaction',{run_id:baseline.run_id});await shot('automatic-turkiye.png');
 await page.getByRole('button',{name:'Su -20%',exact:true}).click();const cutWait=waitPost();await page.getByRole('button',{name:'ÜRÜN DESENİNİ HESAPLA',exact:true}).click();const cut=await(await cutWait).json();assert.ok(cut.optimized.totals.water_m3<baseline.optimized.totals.water_m3*.801);check('Automatic start preserves explicit water -20% scenario rerun');
 const otherWait=waitPost();await page.getByLabel('Çalışma bölgesi',{exact:true}).selectOption('gap_sanliurfa');const other=await(await otherWait).json();assert.equal(other.request.region_id,'gap_sanliurfa');assert.equal(other.optimized.crops.length,4);check('Selecting Şanlıurfa automatically calculates its official four-crop baseline without manual inputs');
 const northWait=autoWait('ec_earth_2030_2049');await page.getByRole('button',{name:'GELECEK / KUZEY',exact:true}).click();const north=await(await northWait).json();assert.equal(north.status,'automatic_analysis_ready');assert.equal(north.production_input_applied,false);assert.equal(north.candidate_analysis.length,3);assert.ok(north.row_count>7000);await page.locator('.automatic-north').waitFor();assert.equal(await page.getByRole('button',{name:'Açıklayıcı senaryoyu yükle',exact:true}).isVisible(),false);assert.equal(await page.getByLabel('Arpa iklim uygunluğu',{exact:true}).isVisible(),false);assert.ok(await page.locator('.automatic-north').getByText(/Bu analiz henüz tam üretim deseni değildir/).isVisible());check('Future North automatically derives climate indicators and three candidate diagnostics while distinguishing missing full-production inputs',{records:north.row_count,production_input_applied:false});
 const wait245=autoWait('nasa_ssp245_2035');await page.getByLabel('Gelecek iklim dönemi',{exact:true}).selectOption('2035');const s245=await(await wait245).json();assert.equal(s245.row_count,365);assert.equal(s245.climate_context_id,'nasa_ssp245_2035');await page.locator('.automatic-north').getByText(/ssp245/).first().waitFor();
 const wait585=autoWait('nasa_ssp585_2035');await page.getByLabel('Gelecek iklim modeli',{exact:true}).selectOption('nasa_ssp585_2035');const s585=await(await wait585).json();assert.equal(s585.climate_context_id,'nasa_ssp585_2035');assert.notEqual(s245.summary.mean_annual_gdd5_c_days,s585.summary.mean_annual_gdd5_c_days);assert.notEqual(s245.summary.mean_annual_precipitation_mm,s585.summary.mean_annual_precipitation_mm);await page.locator('.automatic-north').getByText(/ssp585/).first().waitFor();check('Selecting SSP245 and SSP585 recomputes different indicators from verified daily data',{ssp245_gdd5:s245.summary.mean_annual_gdd5_c_days,ssp585_gdd5:s585.summary.mean_annual_gdd5_c_days,ssp245_precipitation:s245.summary.mean_annual_precipitation_mm,ssp585_precipitation:s585.summary.mean_annual_precipitation_mm});await shot('automatic-north.png');
 assert.equal(s585.production_input_applied,false);assert.ok(s585.blockers.some(b=>b.id==='water_access'));assert.ok(s585.candidate_analysis.every(c=>c.local_yield_kg_ha===null));check('Automatic diagnosis does not fabricate local yield, water allocation or claim optimizer coefficients are connected');
 await page.getByText('Mühendislik senaryosu deneyi',{exact:true}).click();await page.getByRole('button',{name:'Açıklayıcı senaryoyu yükle',exact:true}).click();const explicitWait=waitPost();await page.getByRole('button',{name:'GELECEĞİN ÜRETİM DESENİNİ HESAPLA',exact:true}).click();const explicit=await(await explicitWait).json();assert.equal(explicit.status,'conditional');assert.equal(explicit.request.climate_context_id,'nasa_ssp585_2035');assert.equal(explicit.classification,'SIMULATION_EXPLANATORY');check('Explicit engineering scenario remains behind collapsed advanced section and is not promoted to sourced production');
 assert.equal(report.errors.length,0);assert.equal(report.http_errors.length,0);assert.equal(report.external_requests.length,0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);report.passed=true;
 }catch(e){report.passed=false;report.failure=String(e);throw e}finally{fs.writeFileSync(path.join(out,'automatic-smoke.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2))}
})().catch(e=>{console.error(e);process.exit(1)});
