const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
 const report={verified_at:new Date().toISOString(),version:'0.5.0',checks:[],screens:[],errors:[],failed:[],blocked_external_requests:[]};
 const out=path.resolve('docs/verification');
 try {
 const context=await browser.newContext({viewport:{width:1366,height:768}});
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(['http:','https:'].includes(u.protocol)&&!['127.0.0.1','localhost'].includes(u.hostname)){report.blocked_external_requests.push(u.href);return r.abort()}return r.continue()});
 const page=await context.newPage();page.setDefaultTimeout(15000);
 page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.failed.push({url:r.url(),status:r.status()})});
 const record=(test,data={})=>{report.checks.push({test,passed:true,...data});console.log('PASS '+test)};
 const call=async(endpoint,button)=>{const waiting=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST');await button.click();const r=await waiting;assert.equal(r.status(),200);return r.json()};
 const run=()=>call('/api/simulate',page.getByRole('button',{name:/^(ÜRÜN DESENİNİ HESAPLA|GELECEĞİN ÜRETİM DESENİNİ HESAPLA)$/}));
 const nav=async title=>{const dialog=page.getByRole('dialog');if(await dialog.count())await page.keyboard.press('Escape');const button=title==='SAHA / PWN'?'SAHA ARAŞTIRMASI':title==='KANIT / VERİ'?'Kanıt / provenans':title;await page.getByRole('button',{name:button,exact:true}).first().click();await page.waitForTimeout(150)};
 const shot=async name=>{await page.evaluate(()=>{scrollTo(0,0);document.querySelector('.analysis-canvas')?.scrollTo(0,0);document.querySelector('.lab-scroll')?.scrollTo(0,0)});await page.screenshot({path:path.join(out,name)});};
 await page.goto('http://127.0.0.1:8000/#turkiye',{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'ÜRÜN DESENİNİ HESAPLA',exact:true}).waitFor();
 const initial=await page.locator('.lab-crop-list input[type=range]').evaluateAll(nodes=>nodes.map(n=>({label:n.getAttribute('aria-label'),top:n.getBoundingClientRect().top,bottom:n.getBoundingClientRect().bottom})));
 const sliderFractions=await page.locator('.lab-crop-list input[type=range]').evaluateAll(nodes=>nodes.map(n=>Number(n.value)/Number(n.max)));assert.ok(sliderFractions[0]>.46&&sliderFractions[0]<.47);assert.ok(sliderFractions[4]<.01);
 const initialFooter=await page.locator('.lab-run-footer').boundingBox();assert.equal(initial.length,5);const layoutOk=initial.every(r=>r.top>=0&&r.bottom<initialFooter.y);report.initial_crop_viewport={passed:layoutOk,initial,initialFooter};assert.ok(initialFooter.y+initialFooter.height<=768);if(layoutOk)record('At 1366×768 all five initial Konya crop sliders and persistent RUN are visible without scrolling');await shot('contract-konya-baseline.png');
 assert.equal(await page.getByRole('button',{name:'Kaynak verisi',exact:true}).count(),0);assert.equal(await page.getByLabel('Sulama verimi',{exact:true}).isDisabled(),false);
 await page.getByLabel('Sulama verimi',{exact:true}).fill('0.7');
 assert.ok(await page.locator('.lab-field-row.overridden').filter({has:page.getByLabel('Sulama verimi',{exact:true})}).getByText('MANUEL SENARYO').isVisible());
 record('Normal inputs are directly editable without source/manual modes and edited values are individually tagged');
 await page.getByRole('button',{name:'Referans',exact:true}).click();assert.equal(await page.getByLabel('Sulama verimi',{exact:true}).inputValue(),'0.75');
 const first=await run();assert.equal(first.status,'conditional');assert.equal(first.optimized.crops.length,5);
 const t=Date.now();await page.getByRole('button',{name:'Su -20%',exact:true}).click();const cut=await run();assert.equal(cut.status,'conditional');assert.ok(cut.optimized.totals.water_m3<first.optimized.totals.water_m3*.801);
 await page.getByRole('button',{name:'Su -20%',exact:true}).click();const repeated=await run();assert.equal(repeated.request.water_sources[0].capacity_m3,cut.request.water_sources[0].capacity_m3);
 const wheat=cut.optimized.crops.find(c=>c.crop_id==='wheat');assert.ok(wheat.summary_reason.includes('minimum üretim'));assert.ok(cut.constraints.find(c=>c.id==='crop_min_output_wheat').binding);
 record('Konya water -20% one-click scenario is repeatable and explanation has binding-constraint evidence',{seconds:(Date.now()-t)/1000,water_m3:cut.optimized.totals.water_m3});
 await shot('contract-konya-stress.png');
 await page.getByRole('button',{name:'Veriler / grafikler',exact:true}).click();assert.ok(await page.locator('.analysis-data svg').count()>=3);await shot('contract-data.png');await page.getByRole('button',{name:'Desen ve kaynaklar',exact:true}).click();record('Same-screen analysis tab exposes source-backed water and production charts plus exact tables');
 const footer=await page.locator('.lab-run-footer').boundingBox();assert.ok(footer.y+footer.height<=768);await page.locator('.analysis-canvas').evaluate(e=>e.scrollTo(0,e.scrollHeight));const footerAfter=await page.locator('.lab-run-footer').boundingBox();assert.equal(footer.y,footerAfter.y);record('Scenario controls and RUN stay visible while result canvas scrolls');
 assert.equal(await page.getByLabel('Sulama verimi',{exact:true}).isDisabled(),false);
 await page.getByRole('button',{name:'HEKTAR',exact:true}).click();await page.getByLabel('Buğday mevcut alan',{exact:true}).fill('590000');assert.ok(await page.getByLabel('Buğday alan payı',{exact:true}).isEnabled());const manual=await run();assert.equal(manual.current.crops.find(c=>c.crop_id==='wheat').area_ha,590000);assert.equal(manual.baseline.crops.find(c=>c.crop_id==='wheat').area_ha,596686.6);record('Direct crop area and share controls preserve official baseline');const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Senaryoyu kaydet',exact:true}).click();const download=await downloadEvent;const savedScenario=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(savedScenario.scenario.crops.find(c=>c.crop_id==='wheat').current_area_ha,590000);assert.equal(savedScenario.classification,'USER_SCENARIO');record('Scenario JSON download contains actual edited input and honest classification');
 await page.getByRole('button',{name:'Referans',exact:true}).click();await page.getByRole('button',{name:'Kuraklık stresi',exact:true}).click();const dry=await run();assert.equal(dry.request.rainfall_factor,.8);assert.equal(dry.request.et0_factor,1.1);assert.ok(dry.current.totals.water_m3>first.current.totals.water_m3);record('Drought quick preset changes declared rainfall and ET0 assumptions');
 await page.getByRole('button',{name:'Referans',exact:true}).click();await page.getByText('+ Aday ürün ekle',{exact:true}).click();await page.getByLabel('Yeni aday ürün',{exact:true}).selectOption('sunflower');await page.getByRole('button',{name:'Ürün ekle',exact:true}).click();await page.getByText('Gelişmiş kısıtlar · Ayçiçeği',{exact:true}).click();await page.getByLabel('Ayçiçeği tarla verimi',{exact:true}).fill('2000');await page.getByLabel('Ayçiçeği iklim uygunluğu',{exact:true}).selectOption('true');await page.getByLabel('Ayçiçeği zemin uygunluğu',{exact:true}).selectOption('true');const added=await run();assert.ok(added.optimized.crops.find(c=>c.crop_id==='sunflower').production_kg>0);record('Candidate crop can be added and activated through explicit manual assumptions');
 await page.getByLabel('Çalışma bölgesi',{exact:true}).selectOption('gap_sanliurfa');await page.waitForFunction(()=>document.querySelector('.lab-heading p')?.textContent.includes('Şanlıurfa'));await page.getByRole('button',{name:'Su -20%',exact:true}).click();const urfa=await run();assert.equal(urfa.optimized.crops.length,4);assert.ok(urfa.optimized.crops.some(c=>c.delta_area_ha<0));record('Single-region workflow generalizes to official Şanlıurfa pattern');await shot('contract-second-region.png');
 await nav('GELECEK / KUZEY');await page.getByRole('button',{name:'GELECEĞİN ÜRETİM DESENİNİ HESAPLA',exact:true}).waitFor();assert.equal(await page.getByLabel('Planlama amacı',{exact:true}).inputValue(),'capacity');assert.equal(await page.getByLabel('Arpa hedef üretim',{exact:true}).isVisible(),false);await shot('contract-north-lab.png');const unknown=await run();assert.equal(unknown.optimized,null);record('Default northern capacity objective does not certify unknown site suitability or expose arbitrary kg targets');
 await page.getByLabel('Gelecek iklim dönemi',{exact:true}).selectOption('2035');await page.getByLabel('Gelecek iklim modeli',{exact:true}).selectOption('nasa_ssp585_2035');
 await page.getByText('Gelecek iklim kanıtı',{exact:true}).click();assert.ok((await page.locator('.lab-climate').innerText()).includes('18,5'));record('Actual NASA SSP585 2035 metrics load as context, separate from production assumptions');
 await page.getByRole('button',{name:'Açıklayıcı senaryoyu yükle',exact:true}).click();assert.equal(await page.getByLabel('Planlama amacı',{exact:true}).inputValue(),'capacity');const capacity=await run();assert.equal(capacity.request.planning_objective,'capacity');assert.equal(capacity.status,'conditional');assert.ok(capacity.objective.normalization_kg);record('Explanatory example preserves capacity objective and computes normalization from resource capacities');
 await page.getByLabel('Planlama amacı',{exact:true}).selectOption('balanced');const north=await run();assert.equal(north.objective.mode,'balanced');assert.ok(north.optimized.crops.every(c=>c.production_kg>0));record('Balanced objective produces all three candidates using explicit max-min capacity logic');assert.equal(north.status,'conditional');assert.equal(north.request.climate_context_id,'nasa_ssp585_2035');assert.equal(north.optimized.crops.length,3);assert.ok(north.provenance.climate_context_integrity.verified);assert.ok(await page.locator('.north-truth-banner').isVisible());record('Three-crop northern result stays explicitly explanatory with selected climate provenance');
 const northFooter=await page.locator('.lab-run-footer').boundingBox();const northViewport=page.viewportSize();assert.ok(northFooter.y>=0&&northFooter.y+northFooter.height<=northViewport.height,JSON.stringify({northFooter,northViewport}));record('Northern sticky RUN remains in viewport when climate controls wrap the topbar');await shot('contract-north-pattern.png');const northRows=await page.locator('.pattern-north .pattern-row').evaluateAll(rows=>rows.map(row=>{const crop=row.querySelector('.pattern-crop strong').getBoundingClientRect(),value=row.querySelector('.pattern-values').getBoundingClientRect();return {crop:row.querySelector('.pattern-crop strong').textContent,name_bottom:crop.bottom,value_bottom:value.bottom,unit:row.querySelector('.pattern-values small').textContent}}));assert.equal(northRows.length,3);assert.ok(northRows.every(r=>r.name_bottom<=768&&r.value_bottom<=768),JSON.stringify(northRows));assert.ok(northRows.some(r=>r.unit==='m²'));record('All three northern crop names and native ha/m² allocation values are visible in the initial desktop result',{rows:northRows});
 await page.getByRole('button',{name:'Veriler / grafikler',exact:true}).click();await page.getByRole('img',{name:'Aylık toplam yağış, milimetre',exact:true}).waitFor();assert.ok(await page.locator('.analysis-data svg').count()>=5);await shot('contract-north-data.png');await page.getByRole('button',{name:'Desen ve kaynaklar',exact:true}).click();record('Verified NASA daily values appear as monthly temperature and precipitation charts; method/source water chart stays separate');
 for(const objective of ['water_priority','energy_priority']){await page.getByLabel('Planlama amacı',{exact:true}).selectOption(objective);const r=await run();assert.equal(r.request.planning_objective,objective);assert.equal(r.status,'conditional');assert.ok(r.objective.stages.includes(objective==='energy_priority'?'min_energy':'min_water'));}record('Water and energy planning objectives retain their explicit solver ordering');
 await page.getByLabel('Planlama amacı',{exact:true}).selectOption('demand');assert.equal(await page.getByLabel('Arpa hedef üretim',{exact:true}).isVisible(),true);const demand=await run();assert.equal(demand.optimized.crops.find(c=>c.crop_id==='barley').production_kg,3000);record('Demand objective exposes the explicit demand basket and preserves legacy reproducibility');
 const sensitivityWait=page.waitForResponse(r=>r.url().endsWith('/api/decision-information')&&r.request().method()==='POST');await nav('SAHA / PWN');const sensitivityResponse=await sensitivityWait;assert.equal(sensitivityResponse.status(),200);const sensitivity=await sensitivityResponse.json();assert.equal(sensitivity.parameters.length,5);assert.equal(sensitivity.parameters.find(p=>p.id==='freshwater').measurable,false);assert.equal(sensitivity.parameters.find(p=>p.id==='temperature').measurable,true);assert.ok(sensitivity.parameters.filter(p=>p.status==='MODEL_LINK_NEEDED').length>=2);await page.getByText('KARAR İÇİN KRİTİK BELİRSİZLİKLER',{exact:true}).waitFor();record('Research drawer calculates five uncertainty rows and separates TASE measurements from terrestrial hydrology and unknown chemistry linkage');await shot('contract-research.png');await page.getByRole('button',{name:'PRE-TASE / gözlem sonrası',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Eşleştir ve deseni yeniden hesapla',exact:true}).isDisabled(),true);
 const saved=await call('/api/simulate',page.getByRole('button',{name:'PRE-TASE desenini kaydet',exact:true}));const field=await call('/api/pattern-field-update',page.getByRole('button',{name:'Eşleştir ve deseni yeniden hesapla',exact:true}));assert.equal(field.before.run_id,saved.run_id);assert.equal(field.before.status,'conditional');assert.equal(field.after.status,'infeasible');assert.equal(field.comparison.calibration_applied,false);const b={...field.before.request},a={...field.after.request};delete b.seawater_temperature_c;delete a.seawater_temperature_c;assert.deepEqual(b,a);record('PRE-TASE snapshot reproduces exact run; post-observation changes only supported temperature input');
 await shot('contract-pre-post.png');
 await page.getByLabel('Gözlem senaryosu sıcaklığı',{exact:true}).fill('10');const same=await call('/api/pattern-field-update',page.getByRole('button',{name:'Eşleştir ve deseni yeniden hesapla',exact:true}));assert.equal(same.changed_pattern,false);record('No pattern change is a valid explicitly reported observation outcome');
 await page.getByLabel(/Zamanı 24 saat kaydır/).check();const bad=await call('/api/pattern-field-update',page.getByRole('button',{name:'Eşleştir ve deseni yeniden hesapla',exact:true}));assert.equal(bad.after,null);record('Invalid time matching prevents post-observation recommendation');
 await nav('GELECEK / KUZEY');await page.getByLabel('Yerel tatlı su kapasitesi',{exact:true}).fill('1999');await nav('SAHA / PWN');assert.equal(await page.getByRole('button',{name:'Eşleştir ve deseni yeniden hesapla',exact:true}).isDisabled(),true);await page.getByText(/Senaryo veya model noktası değişti/).waitFor();record('Editing planning assumptions cannot silently mutate the saved PRE-TASE baseline');
 await page.getByRole('button',{name:'PWN profil / CSV',exact:true}).click();const waiting=page.waitForResponse(r=>r.url().endsWith('/api/pwn/example'));await page.getByRole('button',{name:'Açıklayıcı simülasyonu yükle',exact:true}).click();assert.equal((await(await waiting).json()).sample_count,61);const csv=await(await context.request.get('http://127.0.0.1:8000/api/pwn/example.csv')).body();await page.getByLabel('PWN CSV dosyası',{exact:true}).setInputFiles({name:'lab-smoke.csv',mimeType:'text/csv',buffer:csv});await page.getByLabel(/^Verinin kaynağı/).selectOption('SIMULATION_EXPLANATORY');await page.getByLabel(/^Derinlik yöntemi/).selectOption('encoder_vertical_tank');const imported=await call('/api/pwn/analyze',page.getByRole('button',{name:'Dosyayı analiz et',exact:true}));assert.ok(imported.raw_saved);record('Existing PWN importer and raw provenance remain working');
 await nav('KANIT / VERİ');await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});record('Evidence drawer keeps keyboard access');
 for(const width of [1366,390]){await page.setViewportSize({width,height:width===390?844:768});for(const title of ['BUGÜN / TÜRKİYE','GELECEK / KUZEY','SAHA / PWN','KANIT / VERİ']){await nav(title);report.screens.push({workspace:title,width,overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)})}}
 await nav('GELECEK / KUZEY');await shot('contract-mobile.png');
 assert.ok(report.initial_crop_viewport.passed,'All five initial crop sliders must be visible at 1366×768');assert.equal(report.errors.length,0);assert.equal(report.failed.length,0);assert.equal(report.blocked_external_requests.length,0);assert.ok(report.screens.every(s=>!s.overflow));report.passed=true;
 }catch(e){report.passed=false;report.failure=String(e);throw e}finally{fs.writeFileSync(path.join(out,'contract-smoke.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2))}
})().catch(e=>{console.error(e);process.exit(1)});


