// Local, offline dashboard verification. Requires Playwright and installed Chrome.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  const external=[],errors=[],failed=[],checks=[],screens=[],mobile=[];
  await context.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&!['localhost','127.0.0.1'].includes(u.hostname)){external.push(u.href);return route.abort();}return route.continue();});
  const page=await context.newPage();
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()});});
  const out=path.resolve('docs/verification');fs.mkdirSync(out,{recursive:true});
  const record=(test,result={})=>checks.push({test,passed:true,...result});
  const go=async hash=>{await page.evaluate(h=>{location.hash=h;},hash);await page.waitForTimeout(250);};
  const call=async(endpoint,button)=>{const response=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST');await button.click();const r=await response;assert.equal(r.status(),200);return r.json();};
  await page.goto('http://127.0.0.1:8000/',{waitUntil:'networkidle'});
  await page.getByRole('heading',{name:'Kuzey üretim karar alanı',exact:true}).waitFor();
  record('Default workspace is northern decision support');
  const calculate=()=>page.getByRole('button',{name:'Üretim kararını hesapla'});
  const first=await call('/api/decision',calculate());
  assert.equal(first.status,'conditional');assert.equal(first.totals.production_kg,1000);
  assert.ok(first.constraints.some(c=>c.binding&&c.id==='freshwater'));
  await page.getByRole('button',{name:'Karşılaştırma için sabitle'}).click();
  await page.getByLabel('Tatlı su',{exact:true}).fill('20');
  assert.ok(await page.getByText(/Gösterilen karar önceki hesaba ait/).isVisible());
  const second=await call('/api/decision',calculate());assert.equal(second.totals.desalinated_water_m3,0);
  assert.ok(second.totals.energy_kwh<first.totals.energy_kwh);
  await page.getByRole('heading',{name:'Sabitlenen durum ↔ güncel hesap'}).waitFor();
  record('Calculate, binding constraints, stale warning, snapshot and changed allocation',{before_kwh:first.totals.energy_kwh,after_kwh:second.totals.energy_kwh});
  await page.getByLabel('Tatlı su',{exact:true}).fill('10');
  await call('/api/decision',calculate());
  await page.screenshot({path:path.join(out,'dashboard-north.png'),fullPage:true});
  await page.getByRole('button',{name:'İklim bağlamı ve kanıt',exact:true}).click();
  await page.getByRole('columnheader',{name:'1995–2014'}).waitFor();
  await page.getByRole('columnheader',{name:'2030–2049'}).waitFor();
  record('Northern model periods and separate literature context visible');
  await page.getByRole('button',{name:'Ölçümün karar etkisi',exact:true}).click();
  await page.getByRole('button',{name:/Enerji eşiği örneği/}).click();
  const field=await call('/api/field-comparison',page.getByRole('button',{name:'Eşleştir ve karar etkisini hesapla'}));
  assert.equal(field.before.status,'conditional');assert.equal(field.after.status,'unsuitable');assert.equal(field.changed_decision,true);
  assert.equal(field.calibration_applied,false);assert.equal(field.confidence_score,null);
  record('Matched simulated field pair changes conditional feasibility at explicit threshold',{before:field.before.status,after:field.after.status,classification:field.classification});
  await page.getByLabel(/Zamanı eşleştirme dışına taşı/).check();
  const mismatch=await call('/api/field-comparison',page.getByRole('button',{name:'Eşleştir ve karar etkisini hesapla'}));
  assert.equal(mismatch.status,'not_comparable');assert.equal(mismatch.after,null);
  record('Time mismatch blocks observation-derived decision update');
  await page.screenshot({path:path.join(out,'dashboard-field.png'),fullPage:true});
  await go('turkiye');
  await page.getByRole('heading',{name:'Türkiye karşılaştırma alanı'}).waitFor();
  assert.equal(await page.locator('.region-checks input:checked').count(),5);
  await page.getByLabel('Net sulama bütçesi',{exact:true}).fill('300');
  const benchmark=await call('/api/benchmark-comparison',page.getByRole('button',{name:'Seçili bölgeleri karşılaştır'}));
  assert.equal(benchmark.sites.length,5);assert.ok(benchmark.sites.some(s=>s.budget_screen.gap_mm>0));
  await page.locator('.region-checks input').last().uncheck();
  const subset=await call('/api/benchmark-comparison',page.getByRole('button',{name:'Seçili bölgeleri karşılaştır'}));assert.equal(subset.sites.length,4);
  await page.locator('.region-checks input').last().check();
  await call('/api/benchmark-comparison',page.getByRole('button',{name:'Seçili bölgeleri karşılaştır'}));
  record('Five-region common-budget comparison and selectable subset');
  await page.screenshot({path:path.join(out,'dashboard-turkiye.png'),fullPage:true});
  await go('pwn');
  let response=page.waitForResponse(r=>r.url().endsWith('/api/pwn/example'));
  await page.getByRole('button',{name:'Açıklayıcı simülasyonu yükle'}).click();
  const profile=await(await response).json();assert.equal(profile.sample_count,61);assert.equal(profile.source_kind,'SIMULATION_EXPLANATORY');
  const csv=await(await context.request.get('http://127.0.0.1:8000/api/pwn/example.csv')).body();
  await page.getByLabel('PWN CSV dosyası',{exact:true}).setInputFiles({name:'dashboard-simulation.csv',mimeType:'text/csv',buffer:csv});
  await page.getByLabel(/^Verinin kaynağı/).selectOption('SIMULATION_EXPLANATORY');
  await page.getByLabel(/^Derinlik yöntemi/).selectOption('encoder_vertical_tank');
  const imported=await call('/api/pwn/analyze',page.getByRole('button',{name:'Dosyayı analiz et'}));
  assert.equal(imported.source_kind,'SIMULATION_EXPLANATORY');assert.ok(imported.raw_saved);
  await page.getByRole('img',{name:'Ham sinyal derinlik profili'}).waitFor();
  await go('evidence');await go('pwn');
  await page.getByRole('img',{name:'Ham sinyal derinlik profili'}).waitFor();
  record('PWN example, CSV provenance and profile persistence across navigation',{sha256:imported.sha256});
  await page.screenshot({path:path.join(out,'dashboard-pwn.png'),fullPage:true});
  await go('north');
  await page.getByRole('button',{name:'Üretim kararı',exact:true}).click();
  await page.getByRole('heading',{name:'Sabitlenen durum ↔ güncel hesap'}).waitFor();
  assert.equal(await page.getByLabel('Enerji bütçesi',{exact:true}).inputValue(),'25110');
  await page.getByLabel('Enerji bütçesi',{exact:true}).fill('0');
  const impossible=await call('/api/decision',calculate());assert.equal(impossible.totals,null);assert.equal(impossible.allocations.length,0);
  record('Global inputs and snapshot persist; impossible budget never invents production');
  await page.getByLabel('Enerji bütçesi',{exact:true}).fill('26000');await call('/api/decision',calculate());
  await page.getByRole('button',{name:'Kanıtları aç',exact:false}).first().click();
  await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
  record('Evidence drawer opens and closes with Escape');
  for(const hash of ['north','turkiye','pwn','evidence','pilot']){await go(hash);screens.push({workspace:hash,title:await page.locator('h1:visible').innerText(),overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});}
  await page.setViewportSize({width:390,height:844});
  for(const hash of ['north','turkiye','pwn','evidence','pilot']){await go(hash);mobile.push({workspace:hash,overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});}
  await go('north');await page.screenshot({path:path.join(out,'dashboard-mobile.png'),fullPage:true});
  const report={verified_at:new Date().toISOString(),version:'0.2.0',screens,mobile,checks,errors,failed,blocked_external_requests:external};
  fs.writeFileSync(path.join(out,'dashboard-smoke.json'),JSON.stringify(report,null,2));
  await browser.close();
  assert.equal(errors.length,0);assert.equal(failed.length,0);assert.equal(external.length,0);assert.ok([...screens,...mobile].every(s=>!s.overflow));
  console.log(JSON.stringify(report,null,2));
})().catch(error=>{console.error(error);process.exit(1);});
