// Desktop end-to-end test for the guided preview. Uses the installed Playwright runtime.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs','verification','jury-demo-029');
fs.mkdirSync(out,{recursive:true});
const frozenDir=path.join(root,'data','north','frozen_runs');
function frozenDigest(){const names=fs.existsSync(frozenDir)?fs.readdirSync(frozenDir).filter(x=>x.endsWith('.json')).sort():[];return crypto.createHash('sha256').update(names.map(x=>x+':'+crypto.createHash('sha256').update(fs.readFileSync(path.join(frozenDir,x))).digest('hex')).join('|')).digest('hex')}
const check=(ok,message)=>{if(!ok)throw Error(message)};
(async()=>{
 const beforeFrozen=frozenDigest(),browser=await chromium.launch({headless:true,channel:'chrome',args:['--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();
 const requests=[],errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))requests.push({path:new URL(r.url()).pathname,method:r.method(),body:r.postData()})});
 await context.route('**/*',route=>{const url=new URL(route.request().url());if(['http:','https:'].includes(url.protocol)&&!['127.0.0.1','localhost'].includes(url.hostname)){external.push(url.href);return route.abort()}return route.continue()});
 await page.goto('http://127.0.0.1:8011/#turkiye',{waitUntil:'domcontentloaded'});
 await page.getByRole('button',{name:/Sıcak ve kurak/}).waitFor({timeout:30000});
 await page.getByRole('button',{name:/Sıcak ve kurak/}).click();
 check(await page.getByRole('button',{name:/Sıcak ve kurak/}).getAttribute('aria-pressed')==='true','Preset scenario not loaded');
 const manualTemperature=page.getByRole('slider',{name:'Sıcaklık değişimi'});
 await manualTemperature.focus();await manualTemperature.press('ArrowRight');
 const manualValue=await manualTemperature.inputValue();check(Number(manualValue)>2,'Manual temperature override not applied');
 const normalResponse=page.waitForResponse(r=>r.url().endsWith('/api/simulate')&&r.request().method()==='POST');
 await page.getByRole('button',{name:/EN UYGUN DESENİ HESAPLA/}).click();
 const normal=await (await normalResponse).json();check(Boolean(normal.run_id),'Normal optimizer result missing');
 await page.locator('#main .live-pattern').getByText('MODEL ÖNERİSİ').waitFor();
 const normalPattern=await page.locator('#main .live-pattern').innerText();
 await page.getByRole('button',{name:'JÜRİ MODU'}).click();
 await page.getByRole('region',{name:'Jüri modu denetimleri'}).getByText('8 adım · 99 sn').waitFor();
 await page.getByRole('button',{name:'Başlat'}).click();
 const dock=page.getByRole('region',{name:'Jüri modu denetimleri'});
 const readyNext=()=>page.waitForFunction(()=>{const button=[...document.querySelectorAll('.jury-controls button')].find(x=>x.textContent==='Sonraki');return button&&!button.disabled},null,{timeout:60000});
 const stages=[];const snap=async(name)=>{await page.screenshot({path:path.join(out,name+'.png')});stages.push({stage:name,title:await dock.locator('b').first().innerText(),overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)})};
 await dock.getByText('KONYA — İLK PİLOT').waitFor();await page.locator('.jury-demo').getByLabel('Konya mevcut ürün deseni').waitFor();await snap('01-konya-baseline');
 await dock.getByRole('button',{name:'Sonraki'}).click();await dock.getByText('SU KOŞULU DEĞİŞİYOR').waitFor();await dock.getByText('ÖNERİLEN DESENİN SU GEREĞİ').waitFor();await readyNext();await snap('02-konya-water20');
 await dock.getByRole('button',{name:'Sonraki'}).click();await dock.getByText('TÜRKİYE — AYNI MOTOR').waitFor();await dock.getByText('Gediz / Manisa').waitFor();await snap('03-gediz-transfer');
 await dock.getByRole('button',{name:'Sonraki'}).click();await dock.getByText('2026 MODEL YILI → GELECEK').waitFor();await readyNext();await page.locator('.jury-demo .ns-main-grid').waitFor({timeout:60000});await snap('04-future-change');
 await dock.getByRole('button',{name:'Sonraki'}).click();await dock.getByText('GELECEĞİN ÜRETİM VE SU YÖNETİMİ PLANI').waitFor();await dock.getByText('YENİ SU GEREĞİ').waitFor();await page.locator('.jury-demo .ns-decision-grid').waitFor();await page.waitForTimeout(500);await snap('05-north-decision');
 await page.getByRole('button',{name:/\+50 yıl/}).click();await page.locator('.jury-demo .north-plan-context').getByText(/2076 model yılı/).waitFor({timeout:60000});await dock.getByText('2076 · SSP245').waitFor();await readyNext();await snap('05b-future-year-change');
 await dock.getByRole('button',{name:'Sonraki'}).click();await page.getByText('ARAŞTIRMAYLA DOĞRULANACAK GİRDİLER').waitFor();await snap('06-field');
 await dock.getByRole('button',{name:'Sonraki'}).click();await page.locator('.jury-pilot').getByText('KONTROLLÜ ÜRETİM DENEYİ').waitFor();await snap('07-controlled-pilot');
 await dock.getByRole('button',{name:'Sonraki'}).click();await dock.getByText('TEK ARAŞTIRMA HATTI').waitFor();await snap('08-continuity');
 await dock.getByRole('button',{name:'Jüri modundan çık'}).click();
 check(await page.getByRole('slider',{name:'Sıcaklık değişimi'}).inputValue()===manualValue,'Manual override not restored');
 check(await page.getByRole('button',{name:'JÜRİ MODU'}).getAttribute('aria-pressed')==='false','Jury mode still active');
 check(await page.locator('#main .live-pattern').getByText('MODEL ÖNERİSİ').isVisible(),'Turkey calculated result not restored');
 check(await page.locator('#main .live-pattern').innerText()===normalPattern,'Turkey calculated result changed after demo');
 await page.getByRole('button',{name:'GELECEK / KUZEY'}).click();
 await page.getByRole('spinbutton',{name:'Simülasyon yılı'}).fill('2036');
 await page.getByRole('button',{name:'Su önceliği'}).click();
 const northNormalResponse=page.waitForResponse(r=>r.url().endsWith('/api/north/plan')&&r.request().postData()?.includes('"target_year":2036'));
 await page.getByRole('button',{name:'Simülasyonu çalıştır'}).click();await northNormalResponse;
 await page.locator('#main .north-plan-context').getByText(/2036 model yılı/).waitFor();
 const normalNorthPlan=await page.locator('#main .ns-main-grid').innerText();
 await page.getByRole('button',{name:'JÜRİ MODU'}).click();await page.getByRole('button',{name:'Başlat'}).click();
 await readyNext();await page.getByRole('button',{name:'Otomatik oynat'}).click();await page.getByRole('region',{name:'Jüri modu denetimleri'}).getByText('SU KOŞULU DEĞİŞİYOR').waitFor({timeout:15000});await page.getByRole('button',{name:'Durdur'}).click();
 await page.keyboard.press('ArrowLeft');await page.getByRole('region',{name:'Jüri modu denetimleri'}).getByText('KONYA — İLK PİLOT').waitFor();
 await readyNext();await page.keyboard.press('ArrowRight');await page.getByRole('region',{name:'Jüri modu denetimleri'}).getByText('SU KOŞULU DEĞİŞİYOR').waitFor();
 await page.getByRole('region',{name:'Jüri modu denetimleri'}).getByRole('button',{name:'Jüri modundan çık'}).click();
 check(await page.getByRole('spinbutton',{name:'Simülasyon yılı'}).inputValue()==='2036','North year not restored');
 check(await page.getByRole('button',{name:'Su önceliği'}).getAttribute('aria-pressed')==='true','North objective not restored');
 check(await page.locator('#main .north-plan-context').getByText(/2036 model yılı/).isVisible(),'North calculated result not restored');
 check(await page.locator('#main .ns-main-grid').innerText()===normalNorthPlan,'North calculated result changed after demo');
 await page.route('**/api/north/plan',route=>route.fulfill({status:503,contentType:'application/json',body:'{"detail":"Demo test kesintisi"}'}));
 await page.getByRole('button',{name:'JÜRİ MODU'}).click();await page.getByRole('button',{name:'Başlat'}).click();
 const failedDock=page.getByRole('region',{name:'Jüri modu denetimleri'});
 await readyNext();await failedDock.getByRole('button',{name:'Sonraki'}).click();
 await readyNext();await failedDock.getByRole('button',{name:'Sonraki'}).click();
 await readyNext();await failedDock.getByRole('button',{name:'Sonraki'}).click();
 await failedDock.getByRole('alert').getByText(/Hesap başarısız/).waitFor({timeout:30000});
 check(await failedDock.getByRole('button',{name:'Sonraki'}).isDisabled(),'Failure allowed progression');
 await failedDock.getByRole('button',{name:'Jüri modundan çık'}).click();await page.unroute('**/api/north/plan');
 check(await page.locator('#main .ns-main-grid').innerText()===normalNorthPlan,'North result changed after demo failure');
 const waterCall=requests.find(x=>x.path==='/api/simulate'&&x.body&&x.body.includes('Su kısıntısı'));
 check(waterCall&&JSON.parse(waterCall.body).water_sources.some(x=>x.capacity_m3>0),'Water preset did not call optimizer');
 check(requests.some(x=>x.path==='/api/simulate'&&x.body&&JSON.parse(x.body).region_id==='gediz_manisa'),'Transfer region did not call optimizer');
 check(requests.some(x=>x.path==='/api/north/plan'&&x.body&&JSON.parse(x.body).target_year===2051),'Future year did not call optimizer');
 check(requests.some(x=>x.path==='/api/north/plan'&&x.body&&JSON.parse(x.body).target_year===2076),'Optional year did not call optimizer');
 check(!requests.some(x=>['/api/north/freeze','/api/north/observe','/api/pattern-field-update'].includes(x.path)),'Demo wrote field observation or PRE snapshot');
 check(frozenDigest()===beforeFrozen,'PRE snapshot files changed');check(errors.length===0,'Browser errors: '+errors.join('; '));check(external.length===0,'External dependency: '+external.join('; '));check(stages.every(x=>!x.overflow),'Desktop horizontal overflow');
 fs.writeFileSync(path.join(out,'browser-qa.json'),JSON.stringify({stages,normal_run_id:normal.run_id,api_calls:requests.filter(x=>['/api/simulate','/api/north/plan','/api/north/reference'].includes(x.path)).map(x=>({path:x.path,region:x.body?JSON.parse(x.body).region_id:undefined,year:x.body?JSON.parse(x.body).target_year:undefined})),errors,external,pre_snapshot_unchanged:true,normal_scenario_restored:true,manual_override_restored:true,normal_result_restored:true,north_year_and_objective_restored:true,north_result_restored:true,autoplay_transition_verified:true,failure_fallback_verified:true},null,2));
 await browser.close();console.log('JURY DEMO OK',stages.map(x=>x.stage).join(', '));
})().catch(error=>{console.error(error);process.exit(1)});
